//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BattleshipService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BattleshipService.IBattleship")]
    public interface IBattleship {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleship/Shoot", ReplyAction="http://tempuri.org/IBattleship/ShootResponse")]
        void Shoot(System.Drawing.Point target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleship/NewPlayer", ReplyAction="http://tempuri.org/IBattleship/NewPlayerResponse")]
        void NewPlayer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleship/StartGameSession", ReplyAction="http://tempuri.org/IBattleship/StartGameSessionResponse")]
        bool StartGameSession();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBattleshipChannel : Client.BattleshipService.IBattleship, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BattleshipClient : System.ServiceModel.ClientBase<Client.BattleshipService.IBattleship>, Client.BattleshipService.IBattleship {
        
        public BattleshipClient() {
        }
        
        public BattleshipClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BattleshipClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BattleshipClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BattleshipClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Shoot(System.Drawing.Point target) {
            base.Channel.Shoot(target);
        }
        
        public void NewPlayer(string name) {
            base.Channel.NewPlayer(name);
        }
        
        public bool StartGameSession() {
            return base.Channel.StartGameSession();
        }
    }
}
